### ISSUE TITLE
White space under message entry field

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1640] opened 2023-07-18 14:47 UTC
Steps to reproduce in 1.5.0 on iPhone SE 1st gen:

1. Open message entry field

Expected: message field is positioned above keyboard with some reasonable margin of white space.
Actual: there is a large area of whitespace  between the keyboard and the message entry field, about as tall as the message entry field itself.

![Image](https://github.com/TryQuiet/quiet/assets/213678/4794410a-8bb8-4549-985e-4686fa7c53e4)

**Comment by siepra** [comment] 2023-09-11 13:10
Duplicate of #1689

**Closed by siepra** 2023-09-11 13:10 UTC
Labels: bug, iOS
