### ISSUE TITLE
Android app loses data, resets to "join community" state

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#415] opened 2022-04-02 17:46 UTC
Steps to reproduce:

1. Join our internal community on mobile
2. Use the app normally for some period

Expected: app keeps working

Actual: eventually the app restarts or is killed, and you get kicked back to the "join community" screen

Notes:

1. It's possible that restarting is the thing that triggers this, i.e. that account state is never saved.
2. When this happened to me, the "reset" happened when I switched to another app. But also it seemed that I had to be in the channel for some amount of time... I'm not sure. 
3. It also seems like it happens more in communities with lots of messages. 
4. App data appears to be saved, because after reset the app is using a lot of data. It looks like it has synced all our community's messages.

**Comment by siepra** [comment] 2022-09-07 08:52
It looks like it's easy to reproduce in a mature community like our own

**Comment by vinkabuki** [comment] 2022-09-08 09:25
Not enough information provided to work on this. No steps to reproduce or even a info when does it happen? on runtime? on restart?

**Comment by holmesworcester** [comment] 2022-09-09 14:39
This looks like one solution:

https://github.com/rt2zz/redux-persist/issues/284 + https://www.npmjs.com/package/redux-persist-filesystem-storage

I'm also curious if there's a way we can store less data in redux persist, e.g. just the latest messages in each channel, the channel list, user info, etc.

**Comment by siepra** [comment] 2022-11-21 14:19
I'm closing this ticket and moving it to "done" column as it's not easily testable by QA and we haven't seen this problem for a few weeks already

**Closed by siepra** 2022-11-21 14:19 UTC
Labels: bug
