### ISSUE TITLE
App stops working after 15 seconds (on a specific device)

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#826] opened 2022-08-17 13:20 UTC
Peers disconnect after 5-15 seconds and do not connect again.

**Comment by siepra** [comment] 2022-08-23 11:48
Problems are probably caused by service running tor being killed by the os (when running out of resources).
We're trying to confirm by resolving https://github.com/TryQuiet/quiet/issues/845

**Comment by holmesworcester** [comment] 2022-09-07 12:19
this still happens? it worked for me for longer than 15 seconds.

**Comment by siepra** [comment] 2022-10-25 14:53
After recent changes related to https://github.com/TryQuiet/quiet/issues/916 this problem should be solved (0.5.4-alpha.3 and above)

**Closed by siepra** 2022-10-25 14:53 UTC
Labels: bug
