### ISSUE TITLE
Warn user of duplicate official name

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#1647] opened 2023-07-19 07:50 UTC

**Comment by kingalg** [comment] 2023-08-01 13:50
Link to figma designs: https://www.figma.com/file/TV9pF84Ob8pLYRLu83gNol/Joining-when-owner-is-offline?type=design&node-id=7-2510&mode=design

Screenshot of designs from figma:

<img width="685" alt="Screenshot 2023-08-01 at 15 43 31" src="https://github.com/TryQuiet/quiet/assets/68909168/1ec645af-3b4c-4843-9667-09d5602b855c">

Details as per discussion in https://github.com/TryQuiet/quiet/issues/1340:
- When there are two or more official users with the same name, we should show a very aggressive full screen warning such as "Warning: impersonation attack. The community owner has given two people the same name. This should never happen, and it means the owner is malicious or compromised."
- "Warning: impersonation attack" should appear "If the owner hands out duplicate names (which should never happen) it should be very visible. On every restart, for example." @holmesworcester as we are about to work on this issue could you confirm:
1) if this should happen on every restart?
2) are there any other situations in which it should appear?

**Comment by holmesworcester** [comment] 2023-08-01 14:39
It should show as soon as we notice it.

On desktop it should show on every restart, but on mobile 'restart' means something different. 

I think it makes sense to redesign this to be an alert banner that displays all the time rather than a full screen thing. Or it could be a full screen warning followed by an alert banner that displays all the time. Let's knock this back to 'needs design' and move it out of the sprint.

**Comment by holmesworcester** [comment] 2023-08-11 16:10
duplicate of #119. closing.

**Closed by holmesworcester** 2023-08-11 16:10 UTC
