### ISSUE TITLE
Trying to join two different communities with misleading prompt

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1847] opened 2023-09-21 13:44 UTC
Version: quiet@2.0.0-alpha.12 (but I doubt that it was introduced in this version. Probably something that was already there)
System: all desktop

Steps to recreate:
1. Have links to two working communities.
2. With third app try to join first community via link but DON'T choose a username
3. Without closing the app click on the link to join second community
4. You will get popup with "You already belong to a community We're sorry but for now you can only be a member of a single community at a time."

Text on the popup suggest that the user will join first community that they tried to join.
What happens: the user join second community (or any community that was clicked as last if there is several of them).

<img width="718" alt="Screenshot 2023-09-21 at 15 37 47" src="https://github.com/TryQuiet/quiet/assets/68909168/3bc9c98a-5d53-491f-916e-b8c7471fe5b3">

@holmesworcester I don't have strong feeling about whether user should join first or last community they try to join but what we have now is misleading, so we need to either make sure that they will join first community as popup suggests or change text of this popup. Let us know what you think is the best idea.

**Comment by holmesworcester** [comment] 2023-09-21 14:00
This is a bug yes. If you are already in a community or joining, you should have to leave it before you can join another.

It took me a few reads to understand what was happening here. In case this restatement is helpful for anyone else, what is happening here is that clicking new join links will keep joining new communities even if the user never left the previous community. People will lose their accounts so this is not desired.

**Comment by kingalg** [comment] 2023-09-22 08:08
@holmesworcester could you let me know at which point I lost you and I will edit it to clarify? I'm fairly sure that we are talking about two different situations. In point 2 it's said "DON'T register username" so the registration process is actually never triggered. We are safe, no one will loose their accounts. It's only for fresh new users that tries to click on joining link for two different communities before entering their username.

**Comment by holmesworcester** [comment] 2023-09-22 11:59
The confusion comes from the word 'register' since registering happens after somebody joins the community. So 'don't register' would mean that they joined but didn't register.

'Don't choose a username' would be more clear.

Okay yes then this isn't as high priority.

**Comment by kingalg** [comment] 2023-09-22 12:26
True, in our current process with unregistered and registered users this may be confusing, I'll change this.

**Comment by holmesworcester** [comment] 2023-10-04 13:38
The solution is that it should follow through on what it says. If the user is in a community (even if they have no chosen a username) they should not join a new community. If current community is set, don't process the invite link in any way.

**Comment by siepra** [comment] 2023-11-08 11:23
@holmesworcester what's the factor determining membership in a community?
Is it:
a) creation of local network data structures
b) broadcasting a CSR
c) connecting to other peer for the first time
d) something else?

In case of an **a** we probably don't have to change anything
In case of a **b**  or **c** we should implement a new feature on UI for letting users "leave" (erase network data structures and start from scratch before they choose a username)

**Comment by holmesworcester** [comment] 2023-11-08 12:43
I think the criteria must be: "user has opened an invite link". Once they have opened an invite link, they have started the process of joining a community and should not accidentally change what community they are joining or have any ambiguity about it.

Once they open an invite link, clicking a new invite link should not join a new community, it should tell them that they are already in a community.

**Comment by siepra** [comment] 2023-11-08 13:55
It fits into the criteria of **a**, which is how it works atm. Does it mean we can close this issue?

**Comment by siepra** [comment] 2023-11-08 14:01
Ok, nevermind. I see the problem is wrong data is being passed under the hood, not the process itself

**Comment by siepra** [comment] 2023-11-13 16:29
@kingalg could you please check it once again? I'm attaching a video that presents it working fine on my end. I also wrote tests for deep linking behavior in both desktop and mobile and they passes as though everything works fine.

Herę are the steps I took:
https://github.com/TryQuiet/quiet/assets/15381135/897ce719-81f2-4a26-a86d-dbaa59219832

Here is the result (couldn't upload the full video as it was too heavy)
<img width="809" alt="Zrzut ekranu 2023-11-13 o 17 21 42" src="https://github.com/TryQuiet/quiet/assets/15381135/bc4c6ce6-b8ec-4fc6-84ed-8c335e956e36">

**Comment by kingalg** [comment] 2023-11-14 11:08
This is still an issue in both old and newest (Version: 2.0.3-alpha.4) version. @siepra and @EmiM 've seen that I was able to reproduce it several times. With the same links Wiktor is joining correctly all times but Emi managed to reproduce it same as I did.

**Comment by siepra** [comment] 2023-11-14 12:52
We still don't know hat the factor is though

**Closed as completed** 2023-11-24 12:58 UTC
Labels: bug
