### ISSUE TITLE
creating channel called "#channel" throws error, shouldn't

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1118] opened 2022-12-14 20:03 UTC
Right now if you try to create a channel called "#channel" it throws an error. It should simply autocorrect it as we would with channel names with other characters. 

Steps to reproduce:

1. create channel called "#channel"

Expected: channel is created called "channel", since it says this is what will happen.

Actual: user gets an error. "Channel name cannot contain any special characters."

All special characters that would result in invalidation should just be removed and the channel should be submitted without them, as long as the channel name would be valid without them.

**Comment by holmesworcester** [comment] 2023-01-10 18:59
@josephlacey this might be a good starter issue too!

**Comment by josephlacey** [comment] 2023-03-01 00:30
@holmesworcester @vinkabuki @EmiM I've made an initial commit for this.  No tests yet because I have a question about intent of the validation.  I've removed the initial pattern check on the channel name to allow hashes (and other randomly tested special characters) to be submitted.  But hashes at the beginning of the string were then tripping the whitespace validation, so I made some adjustments to that regex to only trigger if the channel name begins with a space or a dash, `-`, or ends with a space or a dash.  Does that match the expectation?

**Comment by holmesworcester** [comment] 2023-03-01 00:43
Yes I think so. Our intent is to standardize usernames, channel names, and community names to make it harder to spoof names or intentionally confuse people. I think what you've done achieves that.

**Comment by josephlacey** [comment] 2023-03-01 00:49
Sweet, thanks @holmesworcester.  

I'll check all the failing tests that have come up on the PR.

**Comment by josephlacey** [comment] 2023-03-01 18:35
> I've removed the initial pattern check on the channel name to allow hashes (and other randomly tested special characters) to be submitted. But hashes at the beginning of the string were then tripping the whitespace validation, so I made some adjustments to that regex to only trigger if the channel name begins with a space or a dash, `-`, or ends with a space or a dash. Does that match the expectation?

Looks like there's a related conversation on #1215

**Comment by holmesworcester** [comment] 2023-03-02 14:05
@josephlacey what's your opinion on this? 

I think any non-permitted character should be treated the same as whitespace, and leading or trailing whitespace should get turned into nothing.  Is this consistent? 

So:

`#channel` -> `channel`
`-channel` -> `channel`
`cool channel` -> `cool-channel`
`#cool###channel-#`-> `cool---channel`

Ideally `cool---channel` would become `cool-channel` also.

I don't want to go crazy about this, but it does seem to help and provide some protection against impersonation.

**Comment by holmesworcester** [comment] 2023-03-02 14:10
I guess the problem with not replacing leading and trailing special characters or spaces with "-" and not allowing `-channel` or `----` is that if we don't allow it, we have to worry about the validation case when somebody tries to be just special characters, whereas if we allow it and replace it we don't. 

I'm okay with allowing `-channel-` or `--channel` or `----` if that makes things simpler and less likely for users to run into validation errors, which I think it does.

**Comment by josephlacey** [comment] 2023-03-03 00:58
> I think any non-permitted character should be treated the same as whitespace, and leading or trailing whitespace should get turned into nothing. Is this consistent?

I would tend to agree with this for simplicity, and doubly so with this other stated goal.

> Our intent is to standardize usernames, channel names, and community names to make it harder to spoof names or intentionally confuse people. I think what you've done achieves that.

A couple of notes:

* Current replacements for what you've written follow the preference, save this one which converts this way,
  * `#cool###channel-#` -> `coolchannel-`
* I'm not sure what rules the replacement code is currently enacting, but I would assume we write the validation to enforce those same rules.  That begs the questions though that if we're altering input to conform to what we choose, the validation functions more like a failsafe, and folks shouldn't general get validation errors.

**Comment by josephlacey** [comment] 2023-03-03 01:00
@holmesworcester 

> I'll check all the failing tests that have come up on the PR.

I've also got fixes for these failing tests, but this might change depending on the above discussion.

**Comment by holmesworcester** [comment] 2023-03-03 01:28
Yeah I think validation as a failsafe (and again on the receiving side) is what we want.

I think it's probably better to turn anything that's not a number or a letter into a hyphen and leave it at that. That way the field is always valid unless it's just empty.

Worrying about trailing or consecutive hyphens might make it nicer but it makes it too complicated.

**Comment by josephlacey** [comment] 2023-03-03 18:45
> I think it's probably better to turn anything that's not a number or a letter into a hyphen and leave it at that. That way the field is always valid unless it's just empty.

Cool.  Currently the parseName function changes spaces to dashes but removes special characters.  That will need to be changed.

> Worrying about trailing or consecutive hyphens might make it nicer but it makes it too complicated.

Works for me.  I've updated the whitespace validation to only check for beginning spaces and dashes, and changed the related error.  

Reading the parseName function, it seems like it should handle the removal of the beginning spaces and dashes as it does with the other special characters, but I'm not seeing that in the UI.  My commits on the PR I've kept to the narrow subject of this issue as changing the parseName function touches on other tickets as well.  Should that be a separate issue?

**Comment by josephlacey** [comment] 2023-03-03 18:45
@holmesworcester Forgot the ping

> > I think it's probably better to turn anything that's not a number or a letter into a hyphen and leave it at that. That way the field is always valid unless it's just empty.
> 
> Cool. Currently the parseName function changes spaces to dashes but removes special characters. That will need to be changed.
> 
> > Worrying about trailing or consecutive hyphens might make it nicer but it makes it too complicated.
> 
> Works for me. I've updated the whitespace validation to only check for beginning spaces and dashes, and changed the related error.
> 
> Reading the parseName function, it seems like it should handle the removal of the beginning spaces and dashes as it does with the other special characters, but I'm not seeing that in the UI. My commits on the PR I've kept to the narrow subject of this issue as changing the parseName function touches on other tickets as well. Should that be a separate issue?

**Comment by holmesworcester** [comment] 2023-03-03 18:51
Yeah can you make a separate issue for that? That seems best.

**Comment by josephlacey** [comment] 2023-03-03 19:07
> Yeah can you make a separate issue for that? That seems best.

#1274

**Comment by josephlacey** [comment] 2023-03-03 19:08
> > Yeah can you make a separate issue for that? That seems best.
> 
> #1274

@holmesworcester I'm going to leave this for you to triage, but feel free to assign it to me if appropriate.

**Comment by holmesworcester** [comment] 2023-03-06 20:44
okay, I moved #1274 to the backlog. 

@josephlacey is the issue described here where users run into a validation error if they type "#channel" fixed now? If so let's move this issue to "waiting for review""

**Comment by josephlacey** [comment] 2023-03-07 00:28
> @josephlacey is the issue described here where users run into a validation error if they type "#channel" fixed now? If so let's move this issue to "waiting for review""

@holmesworcester This should be working based on the original scope, yeah.

A couple of review notes though

- The last commit I pushed passed all the automated tests except the Visual regression testing with Chromatic.  But that's been the case with all my commits, and as far as I read the error, it's a missing account access token rather than an issue with the test itself.  This could be a permission error if the token is stored in a GitHub Secret and my account doesn't have access to them, but that's only speculative.  Not sure why they're all resulting this way.
- I tried to triple check the tests locally, but now I'm getting a bunch of environment issues with this branch.  The potential for this crossed my mind with a few of the other PR's as well, but I hadn't seen it yet.  I started working on this issue well before the current the develop branch had been assembled, and I wonder if some of the package versions are out of sync now with some of the tools and if that's going to get in the way of the review.  The changes themselves are very narrow, but I may need to rebase all these changes to be more up to date.

**Comment by holmesworcester** [comment] 2023-03-07 02:46
Somebody else on the team should review this. @Kacper-RF or @EmiM can you tell us what if anything needs to happen here to get tests to pass?

**Comment by EmiM** [comment] 2023-03-07 11:00
@holmesworcester maybe we need to add @josephlacey as chromatic external collaborator to make it work? There is an invitation link I can share.
He would have to sign in to chromatic via github.
I am not 100% it would work, just a thought.

**Comment by holmesworcester** [comment] 2023-03-07 12:35
Yes please try that!

**Comment by EmiM** [comment] 2023-03-07 13:00
Ok, I need a way to DM @josephlacey

**Comment by josephlacey** [comment] 2023-03-08 00:02
@vinkabuki Unfortunately it looks like the Chromatic tests on the related PR are still failing after connecting my Chromatic and Github accounts.  Not sure what the next steps to debug are.

Additionally a couple of the E2E tests are also now failing.  I started this branch off a previous version of develop and wonder if it's out of date with some of the tooling.  Thoughts?

**Comment by Kacper-RF** [comment] 2023-03-08 10:47
@josephlacey I rerun CI with E2E tests, and they passed. Today I will add update for stability for these tests.

**Comment by holmesworcester** [comment] 2023-03-19 15:31
If tests are passing this should be moved to ready for QA and merged to develop

**Comment by vinkabuki** [comment] 2023-03-23 09:16
@josephlacey AFAIK you must create PR "within" repo to use secrets. ATM it's from fork: https://github.com/josephlacey/quiet/tree/fix/1118, so I think there is no other way than creating another PR as regular contributor within organization

**Comment by josephlacey** [comment] 2023-03-23 16:27
> @josephlacey AFAIK you must create PR "within" repo to use secrets. ATM it's from fork: https://github.com/josephlacey/quiet/tree/fix/1118, so I think there is no other way than creating another PR as regular contributor within organization

@vinkabuki Yeah, that's what we've found.  PR's from forks can't access secrets for security reasons, and the triage role in Github, which I have, can't open PR's from with the repo.  I've got a task to document how outside contributors can manually push the Chromatic tests, which is the outstanding issue here.

**Comment by josephlacey** [comment] 2023-03-28 17:59
> Are there corresponding chromatic tests? I can't find it.

@vinkabuki Just submitted these to the PR, #1261.  Everything's passing.

> I think he means the chromatic tests were the thing that didn't run. It doesn't seem like this issue would change the chromatic tests.

I don't think they do, but I've submitted them for completeness sake.

> @josephlacey so our workflow is for someone else to submit the PR by bringing your fork to their own branch and then submitting a PR based on that?

@holmesworcester I still need to write this up (I should create an issue for that), but it's a little less complicated.  Submitting the PR from a forked branch is totally fine and a normal GitHub workflow.  There's just a second step.  

There's an `npm` shortcut included in the desktop package that submits the PR branch to Chromatic from the local cli, but you need to pass in Quiet's Chromatic Project Token as an environment variable.  This is what I do.  So PRs from trusted sources could have the token shared with them along with some documentation to get those outside contributions fully tested.  Otherwise someone with access to the token would need to submit those tests on their behalf.  An extra step in both cases, but not a super tedious one at our current scale.

**Comment by holmesworcester** [comment] 2023-03-28 19:49
This sounds good!

**Closed** 2023-03-30 07:52 UTC
Labels: bug, good first issue

**Comment by kingalg** [comment] 2023-04-11 10:33
Version: 1.2.0-alpha.24

Looks ok, but I wanted to make sure that everything really is working as expected (through this issue there was a lot of different ideas of how some elements should behave and I there is no summary so @josephlacey or @holmesworcester please let me know if this is what I should put to my tests list):

1. " space" -> "Name cannot begin with whitespaces or dashes"
![Image](https://user-images.githubusercontent.com/68909168/231131370-0f0c8380-2f65-48f5-a40c-28c25a223940.png)

2. "-dash1" -> "Name cannot begin with whitespaces or dashes"
![Image](https://user-images.githubusercontent.com/68909168/231132732-eef1475f-7413-460c-8dd3-3fdd40d4f912.png)

3. "white space" -> "white-space"
![Image](https://user-images.githubusercontent.com/68909168/231133042-856fa8fc-e7f7-4229-af3d-3b9042df0d17.png)

4. "#character" -> "character"
![Image](https://user-images.githubusercontent.com/68909168/231133387-f765477c-6db0-4737-b3bd-ae5cf0db70ed.png)

5. "dash--dashdash" -> "dash-dashdash" (same with more dashes)
![Image](https://user-images.githubusercontent.com/68909168/231133873-0ad66ca2-5c7f-4f39-a7aa-be830d1b2983.png)

6. "dash-" -> "dash"
![Image](https://user-images.githubusercontent.com/68909168/231134006-7a280d3d-9b93-4e67-add2-7ad4da3d6050.png)

7. "sigh#" -> "sign"
![Image](https://user-images.githubusercontent.com/68909168/231134330-34a07300-bfb2-4845-92fd-48cc3bdb398e.png)

8. "sign##sign" -> "signsign"
![Image](https://user-images.githubusercontent.com/68909168/231134469-cfa53310-ae7d-4f7e-b8d5-e6c4e39071a9.png)

9. "sign#-dash" -> "sign-dash"
![Image](https://user-images.githubusercontent.com/68909168/231134633-45083a9b-a095-4ddc-8eab-b2ac95d89c69.png)


I've checked more combinations but didn't want to overflow you with examples. I think that those should cover enough.

**Comment by josephlacey** [comment] 2023-04-11 16:22
> Looks ok, but I wanted to make sure that everything really is working as expected (through this issue there was a lot of different ideas of how some elements should behave and I there is no summary so @josephlacey or @holmesworcester please let me know if this is what I should put to my tests list):

@kingalg Yes, these are what I would expect with the current configuration.  Thanks for the all the screen shots!  Makes it easy to confirm.

**Comment by kingalg** [comment] 2023-04-12 09:22
@josephlacey so I consider it done in Version: 1.2.0-alpha.24 (it's easier to me with screen shots as well, sometimes descriptions only require more explanations afterwords and with screens everyone see the same thing)
