### ISSUE TITLE
Use pageup/down to scroll (desktop)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1091] opened 2022-12-08 12:44 UTC
We are about to add multi-line messages, which will require being able to navigate in the text entry field with uparrow. But currently uparrow will scroll the user up the page. 

So we need to use another key combination for scrolling. 

I think Slack does pageup and pagedown for scrolling, so let's do that. Each click should take you up or down a page. 

Related to #1087

**Comment by josephlacey** [comment] 2023-01-27 18:03
I've been working on this one.  I've gotten `Home` and `End` to work as expected, but `PageUp` and `PageDown` are eluding me at the moment.  Hopefully I'll have a PR for this soon.

**Comment by josephlacey** [comment] 2023-02-22 23:43
PR #1250 includes the code changes and test for this feature.  I removed my initial `Home` and `End` implementation as those weren't defined and there's some ambiguity about expectation for what those do.  Probably worth opening another issue for that discussion at some point.

While writing the tests, I had to fix the errors I have getting with the existing visual regression tests.  Cypress was throwing this error,

> The "type" environment variable is unknown.
> Expected: "actual" or "base"
> Actual: undefined

This is generally defined with an environment variable.  Is the expectation that I have a config for that locally?  Or could I be running Cypress from the wrong root?

Fixing this error to generate the tests did reveal error thresholds with the existing regression visual tests, e.g.

> The "after launch" image is different. Threshold limit exceeded!
> Expected: 0
> Actual: 0.08168454365646338

I compared the base snapshots with the ones generated during my test runs and they indeed are notably different.  Again this should probably go to another issue, but I can create that and check all these snapshots and regenerate the base snapshots if need be.

**Comment by josephlacey** [comment] 2023-02-22 23:54
> Fixing this error to generate the tests did reveal error thresholds with the existing regression visual tests, e.g.
> 
> > The "after launch" image is different. Threshold limit exceeded!
> > Expected: 0
> > Actual: 0.08168454365646338
> 
> I compared the base snapshots with the ones generated during my test runs and they indeed are notably different. Again this should probably go to another issue, but I can create that and check all these snapshots and regenerate the base snapshots if need be.

Actually it looks like the base snapshots that GitHub uses are different from the ones my local testing uses,

https://github.com/TryQuiet/quiet/actions/runs/4247906603/jobs/7386468419

Advice on the best way to see these images to confirm these are failures?  And then to generate and commit the correct ones?

**Comment by holmesworcester** [comment] 2023-02-23 19:42
@EmiM or @vinkabuki do you know how to see these screenshots from the tests and update them?

**Comment by EmiM** [comment] 2023-02-23 21:00
Files generated on CI are available on jobs summary page: https://github.com/TryQuiet/quiet/actions/runs/4247906603, on the bottom in "Artifacts" section.

**Comment by josephlacey** [comment] 2023-02-24 02:04
Sweet, thanks @EmiM. 

My eye test between the base and actual images that GitHub generated isn't noticeable.  And the machine-generated diff images also show what's probably a library difference, so I committed the actual images that GitHub created as the new base images.  Running the tests locally now fail for these new tests, but by the same threshold as the existing ones, `0.08780319874242458`, and GitHub is passing them.  I'm assuming this is fine, but let me know if this is the wrong way to fix this.

Not sure if others are having the same failures locally I'm seeing, but we could increase the failure threshold if it's worth having these pass locally as well.

**Comment by holmesworcester** [comment] 2023-03-07 14:16
Just a reminder we need to get this done: https://github.com/TryQuiet/quiet/pull/1250#issuecomment-1452244713

**Comment by kingalg** [comment] 2023-03-15 13:30
Version: 1.1.0-alpha.4

I think that I know what is expected behaviour but just to be sure that I'm not making assumptions:

1. with PgUp and PgDown (or fn+arrow up/down on machines without separate buttons for Pg Up/Down) user is able to scroll already send messages in a channel that is currently open,
2. it should be independent from what is going on on typing field (doesn't matter if the user has a cursor there, if he started to type message, etc. - those functions should have no impact on each other at all),
3. currently if I go to the settings and I use PgUp/Down it scrolls whatever channel is in the background - doesn't sound like a big deal but I would consider it unexpected behaviour. 

@josephlacey let me know if I'm right with those.

**Comment by josephlacey** [comment] 2023-03-15 17:56
> Version: 1.1.0-alpha.4
> 
> I think that I know what is expected behaviour but just to be sure that I'm not making assumptions:
> 
>     1. with PgUp and PgDown (or fn+arrow up/down on machines without separate buttons for Pg Up/Down) user is able to scroll already send messages in a channel that is currently open,
> 
>     2. it should be independent from what is going on on typing field (doesn't matter if the user has a cursor there, if he started to type message, etc. - those functions should have no impact on each other at all),

@kingalg Yes, to these two.  That's how I understand the initial spec.  When composing a message, the arrow keys stay in the compose message field.  This has the added effect that when on the bottom line and clicking the down arrow, I believe it takes you to the end of the bottom line, and similarly when on the top line and clicking the up arrow, I believe it takes you to the beginning of the  top line.

Page up and down are now used to scroll the message list while maintaining typing focus in the message compose field.
 
>     3. currently if I go to the settings and I use PgUp/Down it scrolls whatever channel is in the background - doesn't sound like a big deal but I would consider it unexpected behaviour.

Settings are rendered in a modal?  I wonder if we can change the focus between the modal and then back to the channel when it's opened and closed respectively. 

---

When I was toying around with this feature, I was also playing with Home and End.  Should those move the message list or move the cursor?  Out of scope here, but maybe something to consider.

**Comment by josephlacey** [comment] 2023-03-15 18:43
> > 2. it should be independent from what is going on on typing field (doesn't matter if the user has a cursor there, if he started to type message, etc. - those functions should have no impact on each other at all),
> >
> 
> @kingalg Yes, to these two. That's how I understand the initial spec. When composing a message, the arrow keys stay in the compose message field. This has the added effect that when on the bottom line and clicking the down arrow, I believe it takes you to the end of the bottom line, and similarly when on the top line and clicking the up arrow, I believe it takes you to the beginning of the top line.

I just tested this locally and neither of these are working, eek.  The up and down arrow keys don't navigate within the message field.  I'm assuming this is a bug that needs to be fixed.

**Comment by josephlacey** [comment] 2023-03-16 00:27
> > > 2. it should be independent from what is going on on typing field (doesn't matter if the user has a cursor there, if he started to type message, etc. - those functions should have no impact on each other at all),
> > 
> > 
> > @kingalg Yes, to these two. That's how I understand the initial spec. When composing a message, the arrow keys stay in the compose message field. This has the added effect that when on the bottom line and clicking the down arrow, I believe it takes you to the end of the bottom line, and similarly when on the top line and clicking the up arrow, I believe it takes you to the beginning of the top line.
> 
> I just tested this locally and neither of these are working, eek. The up and down arrow keys don't navigate within the message field. I'm assuming this is a bug that needs to be fixed.

I've hit a wall with debugging this today.  LeftArrow and RightArrow work as expected, going from character to character, including going to the previous or next lines. (The Home and End also work, moving the cursor to the beginning and end of the line respectively).  But UpArrow and DownArrow don't move the cursor at all.  Could this be because the HTML Element is a div and not an textfield or textarea?  That's only explanation I have at the moment.

**Comment by josephlacey** [comment] 2023-03-16 19:02
> > > > 2. it should be independent from what is going on on typing field (doesn't matter if the user has a cursor there, if he started to type message, etc. - those functions should have no impact on each other at all),
> > > 
> > > @kingalg Yes, to these two. That's how I understand the initial spec. When composing a message, the arrow keys stay in the compose message field. This has the added effect that when on the bottom line and clicking the down arrow, I believe it takes you to the end of the bottom line, and similarly when on the top line and clicking the up arrow, I believe it takes you to the beginning of the top line.
> > 
> > I just tested this locally and neither of these are working, eek. The up and down arrow keys don't navigate within the message field. I'm assuming this is a bug that needs to be fixed.
> 
> I've hit a wall with debugging this today. LeftArrow and RightArrow work as expected, going from character to character, including going to the previous or next lines. (The Home and End also work, moving the cursor to the beginning and end of the line respectively). But UpArrow and DownArrow don't move the cursor at all. Could this be because the HTML Element is a div and not an textfield or textarea? That's only explanation I have at the moment.

@kingalg This does seem to be the case, at least as far as I read.  Not exactly sure what the best way forward here is.

**Comment by kingalg** [comment] 2023-03-17 09:27
> 3. currently if I go to the settings and I use PgUp/Down it scrolls whatever channel is in the background - doesn't sound like a big deal but I would consider it unexpected behaviour.
> 
> Settings are rendered in a modal? I wonder if we can change the focus between the modal and then back to the channel when it's opened and closed respectively.

Don't worry about this one. We have several functions that work in a background of Settings modal. This is definitely a bug but it deserves it's own issue, so I will create one for this. 



> > > > > 2. it should be independent from what is going on on typing field (doesn't matter if the user has a cursor there, if he started to type message, etc. - those functions should have no impact on each other at all),
> > > > 
> > > > 
> > > > @kingalg Yes, to these two. That's how I understand the initial spec. When composing a message, the arrow keys stay in the compose message field. This has the added effect that when on the bottom line and clicking the down arrow, I believe it takes you to the end of the bottom line, and similarly when on the top line and clicking the up arrow, I believe it takes you to the beginning of the top line.
> > > 
> > > 
> > > I just tested this locally and neither of these are working, eek. The up and down arrow keys don't navigate within the message field. I'm assuming this is a bug that needs to be fixed.
> > 
> > 
> > I've hit a wall with debugging this today. LeftArrow and RightArrow work as expected, going from character to character, including going to the previous or next lines. (The Home and End also work, moving the cursor to the beginning and end of the line respectively). But UpArrow and DownArrow don't move the cursor at all. Could this be because the HTML Element is a div and not an textfield or textarea? That's only explanation I have at the moment.
> 
> @kingalg This does seem to be the case, at least as far as I read. Not exactly sure what the best way forward here is.

We will discuss this on todays meeting in a few minutes, maybe someone from the team has any ideas, and I will come back to you.

**Comment by siepra** [comment] 2023-03-17 09:50
@josephlacey take a look at `ChannelMessages.tsx:104` . If I get it right, that's probably what messes things up
```
  const handleKeyDown = useCallback<(evt: KeyboardEvent) => void>(
    evt => {
      switch (evt.key) {
        case 'ArrowUp':
          listRef.current?.focus()
          break
        case 'ArrowDown':
          listRef.current?.focus()
          break
      }
    },
  [listRef]
  )
```

**Comment by kingalg** [comment] 2023-03-17 09:57
@josephlacey I read your messages again and I think that we have two issues here - your scroll with PgUp and PgDown is working as expected but arrows in a field messages are not working correctly. Which we already knew and I agreed with Holmes a couple days ago that we are going to have another issue for this (you can see discussion somewhere in "qa" channel on our team-quiet. We could never navigate text in field message because up and down arrows had different function assigned to them. So this is something that we want to fix but it's not scroll related. I consider issue with scroll working good and I'm going to close it, but if you still want to handle arrows in text field I'll assign it to you after I create it. Does it sound good?

**Comment by kingalg** [comment] 2023-03-17 10:01
@josephlacey #1339 this is a new task that I've created for arrows in a field message problem.

**Comment by josephlacey** [comment] 2023-03-17 18:50
@kingalg Awesome, this all sounds great.  Yes, I can assign myself that issue and figure out a solution.

**Closed** 2023-03-21 09:32 UTC
Labels: good first issue
