### ISSUE TITLE
Allow users without certificate to send messages, display messages

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#1646] opened 2023-07-19 05:17 UTC
We should not implement any new schema, but use CSRs for that and replace them with certificates once signed.

**Comment by vinkabuki** [comment] 2023-09-04 09:11
* User without certificate should be able to send a message (maybe we should just simply make signature optional and mark messages as verified and unverified?). ideally we sign messages anyway, but do not check certs, so we have kind of backward compatibility once user got its certificate we know that previous messages are valid.

* it's hard, because users will produce both signed and unsigned messages (my intuition is some UI indicator e.g 'message not verified with some explanation that message was sent before user got his cert)


* All users should display messages from unregistered users. (remove signature and schema checks at different layers of the app) and maybe let's do general solution and focus message validation into single place so it's maintainable.

**Comment by siepra** [comment] 2023-09-04 11:40
Here is how messages verification works right now:
1. In `backend/storage.service.ts:402` there's a method for verifying message's signature
2. Result of verification is being stored as a message object's property (boolean)
3. All the messages are being passed down to state-manager
4. State-manager stores the information about message verification status in redux (`state-manager/verifyMessages.saga.ts`)
5. Unverified messages are being filtered out by the selector (`state-manager/messages.selectors.ts:67`)

**Comment by vinkabuki** [comment] 2023-09-04 11:57
CSR contains same data as certificate (dm key, onion address, peerid, nickname)

**Comment by siepra** [comment] 2023-09-04 12:13
As CSR's are not being shared between client's, how can we assign a username to a sent message having only the public key of a sender?

**Comment by holmesworcester** [comment] 2023-09-05 16:52
> Is there any difference between unconfirmed messages and potential spoofing?

In case this is helpful, we have two classes of "Potential spoofing" for unverified messages (messages from unregistered users):

1. the username of an unregistered user matches another unregistered or registered user. #1559 
2. the username of a registered user matches the username of another unregistered user (the mapping of keys:users is not 1:1)  #119

**Comment by holmesworcester** [comment] 2023-09-05 16:54
Also, is this issue a duplicate of #1759 ?

**Comment by kingalg** [comment] 2023-10-23 12:20
Version: 2.0.1-alpha.7
mobile@2.0.0-alpha.21 (iOS 319)

It's working on both mobile and desktop. All bugs related to certificates are reported in separate issues.

**Closed by kingalg** 2023-10-23 12:20 UTC
