### ISSUE TITLE
User should be able to scroll up to see old messages in the current channel, just using keyboard

### ISSUE THREAD

**Issue by pdurbin** [TryQuiet/quiet#542] opened 2022-05-27 15:42 UTC
@holmesworcester is able to scroll up in the conversation area using ChromeOS by hitting Cmd-UpArrow.

He and I discovered Cmd-UpArrow works on Mac (I'm on macOS 10.15.7) but only after you select the conversation area with your mouse. There is no known way to select the conversation area with your keyboard.

In practice, this means that Mac users must reach for their mouse to scroll up in a conversation.

**Comment by pdurbin** [comment] 2022-06-14 16:43
Hi! I'm running 0.8.1-alpha.0, which is later than the 0.8.0 milestone for this issue, and I'm still having trouble on Mac.

Am I supposed to be able to Shift-tab to the conversation? If the input area is selected and I hit Shift-Tab, I am brought to the list of channels (#zcash is last in the list) rather than the conversation area.

In practice, I'm still finding that if I want to do any scrolling, I have to use my mouse to select the conversation area. Am I missing something?

**Comment by holmesworcester** [comment] 2022-06-14 19:10
@siepra what's the current keyboard shortcut for scrolling up?

**Comment by holmesworcester** [comment] 2022-06-15 12:21
Note: the purpose of the ticket was misunderstood here. PageUp/PageDown does not actually let users scroll up in the conversation area.

**Comment by siepra** [comment] 2022-06-21 12:26
Related PR https://github.com/TryQuiet/monorepo/pull/634

**Comment by kingalg** [comment] 2022-06-21 15:42
v 0.8.3-alpha.0

How it's currently working - if cursor is focused on text field the user can use arrow up to move to see older messages and use arrows up and down to scroll them.
What I don't like about this solution - (1) user can come back to the text field only using tab. If he left this box with arrows he should be able to come back with an arrow as well (that is how slack done it). (2) If the user is writing a message he can use arrows left and right to move through the message but can't use up and down arrows because it automatically takes him area where he can see previously send messages. This is unexpected behaviour and therefore is an accessibility issue.

What would be really good solution - moving with arrows to scroll older messages is in general good and widely used solution. But some things regarding keyboard shortcuts and focus should be fixed. 
- once the user scroll all the way down to the newest message arrow down should take him back to the text field. If arrow up let the user to leave text field expected behaviour would be that arrow down let him go back. 
- once the user start typing arrow up and down should be disable for scrolling to allow the user to easily edit message using keyboard - what I saw on another app was letting user that is already typing to go to send messages field with alt+tab (or command+tab on Mac) and then allow to scroll with arrows up and down.

@holmesworcester can you have a look at that? Because what @siepra did is working as he was planning but I think that we had some controls chosen wrongly at the planning level and now it's working quite strange.

**Comment by kingalg** [comment] 2022-07-08 09:06
@holmesworcester please have a look at the above message and let me know what is your decision.

**Comment by holmesworcester** [comment] 2022-08-09 15:16
Yes, this is annoying and I've created an issue for it here: https://github.com/TryQuiet/quiet/issues/669

**Comment by kingalg** [comment] 2022-08-15 12:50
This issue solution met most of criteria included in initial post. Rest of them were addressed in #669 as was mentioned in previous comment.

**Closed by kingalg** 2022-08-15 12:50 UTC

**Comment by pdurbin** [comment] 2022-08-22 19:05
Thanks, in practice, as of 0.10.1-alpha.1, my workflow for reading unread channels looks something like this:

- Hit Tab until an unread channel has focus. Hit Enter to select.
- Hit up-arrow as needed to scroll up to unread content.
- Repeat.

In practice, this mean I hit Tab a lot to switch channels (Slack has a keyboard shortcut for this). I'm happy to open an issue about this. Please just let me know.

Thanks for working on the scrolling! It's much better!
